apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app-deployment
  labels:
    app: aspnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
        - name: aspnet-app-container
          image: localhost:5000/swapi:latest
          ports:
            - containerPort: 5010
