apiVersion: v1
kind: Service
metadata:
  name: aspnet-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 5010
      targetPort: 5010
      protocol: TCP
      name: http
  selector:
    app: aspnet-app
